name: fitness_tracker_frontend
description: "Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4
  smooth_page_indicator: ^1.2.1
  intl: ^0.20.2
  dashed_circular_progress_bar: ^0.0.6
  fl_chart: ^1.1.1
  zo_animated_border: ^1.0.4
  firebase_core: ^3.15.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.6.0
  path_provider: ^2.1.1
  google_sign_in: ^7.2.0
  flutter_svg: ^2.0.9
  flutter_glass_morphism: ^1.0.2
  http: ^1.1.0
  email_otp: ^3.0.2
  google_generative_ai: ^0.4.7
  permission_handler: ^11.3.0
  google_fonts: ^6.1.0


  path: any
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/assets/icons/app-logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/fonts/
    - lib/assets/icons/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: lib/assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Ubuntu-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
